name: Deployment (develop)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Needed for AWS OIDC
  contents: read # Needed to check out the repository

jobs:
  deploy:
    name: Deploy (develop)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
      deployment_url: https://signal.dev.yourssu.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
