name: Deployment (Production)

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:

permissions:
  id-token: write # Needed for AWS OIDC
  contents: read # Needed to check out the repository

jobs:
  deploy:
    name: Deploy (production)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      deployment_url: https://signal.yourssu.com
      aws_role_arn: arn:aws:iam::590662143928:role/signal-client-deploy-prod
