name: Deployment (develop)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Needed for AWS OIDC
  contents: read # Needed to check out the repository

jobs:
  deploy:
    name: Deploy (develop)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
      deployment_url: https://signal.dev.yourssu.com
      aws_role_arn: arn:aws:iam::590662143928:role/signal-client-deploy-dev
