name: Deployment (Production)

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:

permissions:
  id-token: write # Needed for AWS OIDC
  contents: read # Needed to check out the repository

jobs:
  deploy:
    name: Deploy (production)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      deployment_url: https://signal.yourssu.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
