name: Deployment (Production)

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy (production)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      deployment_url: https://signal.yourssu.com
      cf_project_name: signal-client-prod
    secrets: inherit
