name: Deployment (develop)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write # Needed for AWS OIDC
  contents: read # Needed to check out the repository

jobs:
  deploy:
    name: Build and Deploy to S3 (Develop)
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Or your preferred Node.js version
          cache: "pnpm" # Cache pnpm dependencies

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
        env:
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # Specify your AWS region

      - name: Upload to S3
        run: |
          aws s3 sync ./dist s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
