name: Deployment (develop)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy (develop)
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
      deployment_url: https://signal-dev.yourssu.com
      cf_project_name: signal-dev
    secrets: inherit
